### ISSUE TITLE
CLI and online validator give different results

### ISSUE THREAD

**Issue by dvillaveces-tq** [CMSgov/hpt-validator-cli#13]
## Issue Report

Some files are marked as 100% valid by the online validator, but not the CLI validator

### Expected behavior

I would expect the same file to give the same result on the CLI and web validator.

### Actual behavior

This [file](https://www.rwjbh.org/documents/billing/mrf/223601678_Trinitas-Regional-Medical-Center_standardcharges.csv) passes the online validator (see screenshot).
![Screenshot 2024-07-30 at 4 20 45 PM](https://github.com/user-attachments/assets/c408b427-4e96-49e2-a61a-ab5ea1a53952)

But the same file throws errors when using the CLI validator:
<img width="729" alt="Screenshot 2024-07-30 at 4 24 08 PM" src="https://github.com/user-attachments/assets/7db08fe9-4981-428d-8a43-26900ab3340a">

1. There is some extra white space around the affirmation value
2. Date is in the wrong format (found after fixing the first issue manually)

### Steps to reproduce the behavior

1. Download the linked [file](https://www.rwjbh.org/documents/billing/mrf/223601678_Trinitas-Regional-Medical-Center_standardcharges.csv) 
2. Run it through the CLI validator using `cms-hpt-validator 223601678_Trinitas-Regional-Medical-Center_standardcharges.csv v2.0.0`
3. Run the same file through the online validator at https://cmsgov.github.io/hpt-tool/online-validator/

**Comment by CarlsonErin** [comment]
We are unable to replicate this issue.  We believe you are using an older version of the CLI.  You can update to the latest version of the cli by running:  npm update -g hpt-validator-cli

**Comment by dvillaveces-tq** [comment]
Thanks, that did it
